# railway.toml configuration for your Go web reconnaissance tool
[build]
  # Set up to use Docker
  dockerfile = "Dockerfile"

[deploy]
  # Configure the deployment process to bind to 0.0.0.0 and use the PORT environment variable
  start_cmd = "./web_recon --mode full --host 0.0.0.0 --port ${PORT}"

[env]
  # Define any environment variables needed for deployment here
  PORT = "8080" 
